#TRK-4F41B1FD
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-agentregistry-ui-svc
  labels:
    app: {{ include "agentregistryui.labels.app" . }}
    component: agentregistry-ui
    name: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "agentregistryui.labels.app" . }}
    component: agentregistry-ui
    name: {{ .Release.Name }}
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
