apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-control-tower-svc
  labels:
    app: {{ include "controltower.labels.app" . }}
    component: control-tower
    name: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "controltower.labels.app" . }}
    component: control-tower
    name: {{ .Release.Name }}
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
