apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-cert-gen-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-cert-gen-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "patch", "get", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-cert-gen-binding
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-cert-gen-sa
roleRef:
  kind: Role
  name: {{ .Release.Name }}-cert-gen-role
  apiGroup: rbac.authorization.k8s.io