#TRK-4F41B1FD
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-keycloak-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "keycloak.labels.app" . }}
    component: keycloak
    name: {{ .Release.Name }}
data:
  hostname: {{ .Values.keycloak.hostname | quote }}