apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    marketplace.cloud.google.com/deploy-info: '{"partner_id": "RYQOOI6yq2", "product_id": "cams", "partner_name": "Covasant"}'
  labels:
    app.kubernetes.io/name: cams
spec:
  descriptor:
    type: "CAMS"
    version: "1.0.0"
    description: "CAMS platform with Keycloak and PostgreSQL"
    maintainers:
      - name: "Covasant"
        email: "support@covasant.io"
  selector:
    matchLabels:
      app.kubernetes.io/name: cams
  componentKinds:
    - group: apps
      kind: Deployment
    - group: apps
      kind: StatefulSet
    - group: ""
      kind: Service
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: Secret
    - group: ""
      kind: PersistentVolumeClaim
    - group: ""
      kind: ServiceAccount
    - group: rbac.authorization.k8s.io
      kind: Role
    - group: rbac.authorization.k8s.io
      kind: RoleBinding
    - group: batch
      kind: Job 