apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-pytmgmt
  labels:
    app: {{ include "pytmgmt.labels.app" . }}
    component: pytmgmt
    name: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "pytmgmt.labels.app" . }}
    component: pytmgmt
    name: {{ .Release.Name }}
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
