apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-cams-api
  labels:
    app: {{ include "camsapi.labels.app" . }}
    component: cams-api
    name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.camsapi.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ include "camsapi.labels.app" . }}
      component: cams-api
      name: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      labels:
        app: {{ include "camsapi.labels.app" . }}
        component: cams-api
        name: {{ .Release.Name }}
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: gcp-rag-volume
          emptyDir: {}

      initContainers:
      - name: wait-for-postgres
        image: postgres:17
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-config-envs
              key: DATABASE_PASSWORD
        command:
        - sh
        - -c
        - |
          until pg_isready -h {{ .Release.Name }}-postgresql-svc -p 5432 -U postgres; do
            echo "Waiting for PostgreSQL...";
            sleep 2;
          done

      containers:
      - name: cams-api
        image: "{{ .Values.camsapi.image.repository }}:{{ .Values.camsapi.image.tag }}"
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8000
            name: http
        env:
          - name: APP_ROLE
            value: "api"
          - name: gcp_credentials_path
            value: "/keys/service-account-key.json"
          - name: AUTH_SERVICE_URL
            value: "https://aifabric.{{ .Values.app.baseDomain }}/api/v1/auth"
          - name: DB_HOST
            value: "{{ .Release.Name }}-postgresql-svc"
          - name: DB_PORT
            value: "5432"
          - name: DB_USER
            valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-config-envs
                  key: DATABASE_USER
          - name: DB_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-config-envs
                  key: DATABASE_PASSWORD
          - name: DB_NAME
            value: "cams"
          - name: PROJECT_ID
            value: "dummy"
          - name: LOCATION
            value: "dummy"
          - name: GCP_CORPUS_BUCKET
            value: "dummy"
          - name: RAG_DEFAULT_EMBEDDING_MODEL
            value: "dummy"
          - name: GCS_DEFAULT_STORAGE_CLASS
            value: "dummy"
          - name: REDIS_DB
            value: "2"
        envFrom:
          - secretRef:
              name: {{ .Release.Name }}-config-envs
        volumeMounts:
          - name: gcp-rag-volume
            mountPath: /tmp/gcp_rag_uploads
        resources:
          {{ toYaml .Values.camsapi.resources | nindent 12 }}
        livenessProbe:
          httpGet:
            path: /docs
            port: http
          initialDelaySeconds: 60
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /docs
            port: http
          initialDelaySeconds: 60
          periodSeconds: 20

      - name: cams-api-worker
        image: "{{ .Values.camsapiworker.image.repository }}:{{ .Values.camsapiworker.image.tag }}"
        imagePullPolicy: IfNotPresent
        env:
          - name: APP_ROLE
            value: "worker"
          - name: gcp_credentials_path
            value: "/keys/service-account-key.json"
          - name: AUTH_SERVICE_URL
            value: "https://aifabric.{{ .Values.app.baseDomain }}/api/v1/auth"
          - name: DB_HOST
            value: "{{ .Release.Name }}-postgresql-svc"
          - name: DB_PORT
            value: "5432"
          - name: DB_USER
            valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-config-envs
                  key: DATABASE_USER
          - name: DB_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-config-envs
                  key: DATABASE_PASSWORD
          - name: DB_NAME
            value: "cams"
          - name: PROJECT_ID
            value: "dummy"
          - name: LOCATION
            value: "dummy"
          - name: GCP_CORPUS_BUCKET
            value: "dummy"
          - name: RAG_DEFAULT_EMBEDDING_MODEL
            value: "dummy"
          - name: GCS_DEFAULT_STORAGE_CLASS
            value: "dummy"
          - name: REDIS_DB
            value: "2"
        envFrom:
          - secretRef:
              name: {{ .Release.Name }}-config-envs
        volumeMounts:
          - name: gcp-rag-volume
            mountPath: /tmp/gcp_rag_uploads
        resources:
          {{ toYaml .Values.camsapiworker.resources | nindent 12 }}
