app:
  baseDomain: example.com
  # Set to true when using self-signed certificates
  # Set to false when using CA-signed certificates (GoDaddy, Let's Encrypt, etc.)
  useSelfSignedCert: true

keycloak:
  image:
    repository: null
    tag: null
  replicas: 1
  port: 80
  hostname: "" # enables customers to set their own dns for keycloak
  resources:
    requests:
      cpu: 1000m
      memory: "512Mi"
    limits:
      memory: "1Gi"
      cpu: 1000m

postgresql:
  image:
    repo: null
    tag: null
  persistence:
    storageClass: standard
    size: 20Gi

postgresqlseeddata:
  image:
    repo: null
    tag: null

jauth:
  image:
    repository: null
    tag: null
  replicas: 1
  resources:
    requests:
      cpu: 500m
      memory: "512Mi"
    limits:
      memory: "1Gi"
      cpu: 1000m

jtmgmt:
  image:
    repository: null
    tag: null
  resources:
    requests:
      cpu: 500m
      memory: "512Mi"
    limits:
      memory: "1Gi"
      cpu: 1000m

pytmgmt:
  image:
    repository: null
    tag: null
  replicas: 1
  resources:
    requests:
      memory: "256Mi"
    limits:
      memory: "512Mi"

agentregistry:
  image:
    repository: null
    tag: null
  replicas: 1
  resources:
    requests:
      cpu: 500m
      memory: "512Mi"
    limits:
      memory: "1Gi"
      cpu: 1000m

camsapi:
  image:
    repository: null
    tag: null
  replicas: 1
  resources:
    requests:
      cpu: 500m
      memory: "512Mi"
    limits:
      memory: "1Gi"
      cpu: 1000m

camsapiworker:
  image:
    repository: null
    tag: null
  replicas: 1
  resources:
    requests:
      cpu: 500m
      memory: "512Mi"
    limits:
      memory: "1Gi"
      cpu: 1000m

agentregistryui:
  image:
    repository: null
    tag: null
  replicas: 1
  resources:
    requests:
      memory: "256Mi"
    limits:
      memory: "512Mi"


nginx:
  image:
    repository: null
    tag: null
  replicas: 1
  port: 443
  resources:
    requests:
      cpu: 250m
      memory: "128Mi"
    limits:
      memory: "256Mi"
      cpu: 500m

litellm:
  image:
    repository: null
    tag: null
  replicas: 1
  resources:
    requests:
      memory: "5Gi"
    limits:
      memory: "5Gi"

controltower:
  image:
    repository: null
    tag: null
  replicas: 1
  resources:
    requests:
      memory: "256Mi"
    limits:
      memory: "512Mi"
